### ISSUE TITLE
Improve User Experience for Potential Contributors 

### ISSUE THREAD

**Issue by lockettm** [webcompat/webcompat.com#1285]
Implement the [user experience research](https://github.com/webcompat/webcompat.com/wiki/User-Experience-Research) to improve the onboarding of new contributors. The goal is to create an informed prototype of possible changes, then test it with users against the current website. 

So far, research has uncovered the following potential improvements:

- [x] Add contributor link to top navigation: #1281
- [x] Add social media icons to footer: #1282 
- [x] Review Join the Team section on home page: #1283 
- [x] Design contact page: #1284
- [x] Revamp contributor page: #1149

**Comment by zoepage** [comment]
@lockettm  I love your work. You did a really good job on research. Thank you! :)
Here is an additional discussion on the "human side" of on boarding new contributors.

https://github.com/webcompat/webcompat.com/issues/1286

**Comment by magsout** [comment]
Very interesting and impressive work @lockettm

**Comment by zoepage** [comment]
Closing as this all gets covered by the refactor in https://github.com/webcompat/webcompat.com/tree/refactor
