### ISSUE TITLE
CONTRIBUTING Guidelines fresh eye review and modifications by @zoepage

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1314]
@zoepage has started to review the Contributing guidelines.

Opening this issue so she can commit step by step her changes on the document.

Also found these previous issues which are worth reviewing too.

* [x] #766 Contributing guide: npm install
* [ ] #1134 CONTRIBUTION Guidelines: clarify the syntax of commits messages and pull requests 
* [x] #1176 contributing guidelines - npm run init

--- edit by @zoepage ---
* [x] `sudo npm run script` -> get rid of sudo
* [x] `npm install -g grunt` -> get rid of global install
* [x] add login step to authorize application at [configuring-the-server section](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#configuring-the-server)
* [x]  fix https://github.com/settings/applications/new

**Comment by zoepage** [comment]
Wow, thank you @karlcow for the pointers. You are truly the kind of issue :)

**Comment by karlcow** [comment]
ahah. I wish (maybe? 🤔 ). But I guess the GitHub search engine is really the king 👑 here.

**Comment by zoepage** [comment]
Addition for the documentation,
`sudo npm` is caused by a non-correct setup and can be [fixed easily](https://coderwall.com/p/t2mc9g/don-t-sudo-npm). Otherwise it might cause a security issue. We should add this to the setup section of the contribute.md

**Comment by zoepage** [comment]
I ran into issues while setting up the project during including the `webcompat-tests` repo to get content for the `see all issues` list.

Although the credentials were correctly added, the error `bad credentials` was displayed and no issues were loaded.

I fixed it with logging in and authorizing the application (again), which is no where described in the CONTRIBUTE.md. It should be added to the `Configuring The Server` section.

**Comment by karlcow** [comment]
@zoepage could you commit against this issue little by little, step by step, each time you found a way to improve. Fresh information is always good to write down now. Atomic commits for each bullet items up there.  Example. 

```
git checkout -b 1314/1
git commit -m `Issue #1314 - Improves the server configuration prose` CONTRIBUTING.md
git push origin 1314/1
```


Thanks.

**Comment by karlcow** [comment]
Oh and in case it helps
http://www.otsukare.info/2016/04/14/git-workflow

**Comment by zoepage** [comment]
@karlcow Will do, but I am restructuring the `CONTRIBUTE.md` and I won't start commiting before having a full plan. Otherwise it probably will end up in a mess. ;)

+1 on the feature/fix per commit

**Comment by karlcow** [comment]
> but I am restructuring the CONTRIBUTE.md

Could you share what are your intents in the restructuring? Share early, ship early. To give the possibility of community participation.

**Comment by miketaylr** [comment]
> #1176 contributing guidelines - npm run init

(pre-emptively marking that one as done, as it's taken care of in #1322.)

**Comment by zoepage** [comment]
@karlcow #766 Contributing guide: npm install was closed. Is there anything I need to still fix / add there?

**Comment by karlcow** [comment]
@zoepage do you mean anything for this issue #1314.

I see #706 and #1134 up there in the comments. :)

**Comment by zoepage** [comment]
@karlcow in #766
