### ISSUE TITLE
Update "join the team" section on index page

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1402]
### ToDos
- [x] replace "Join the Team" with “Help Us Improve the Web”
- [x] replace “Learn More” with “Learn more about how to contribute”
- [x]  Adding additional context under “Bug Reporting”
```
Report compatibility issues that you come across on the web.
Report Bugs (link / event is the same)
```

- [x]  Adding additional context under “Bug Diagnosis”
```
Figure out what is causing the issue and help to find a fix.  
Diagnose Bugs (link is the same)
```

- [x]  Adding additional context under “Site Outreach”
```
Locate a contact and reach out to sites to help solve the issue.
Reach out to sites (link is the same)
```
- [x] replace "Bug reporting" icon with https://thenounproject.com/search/?q=report&i=883147
- [x] replace "Bug Diagnosis" icon with https://thenounproject.com/search/?q=diagnose&i=241273
- [x] replace "Site Outreach" icon with https://thenounproject.com/search/?similar=518092&i=518087

- [x] change credentials for icons in https://github.com/webcompat/webcompat.com/blob/master/README.md#icons

---
### Context
Follow up for https://github.com/webcompat/webcompat.com/issues/1283#issuecomment-284574330 and https://github.com/webcompat/webcompat.com/issues/1374#issuecomment-283906535

@lockettm proposed following changes to the content on the "join the team" section on the index page.

> - Replacing "Join the Team" with “Help Us Improve the Web.” One user read this while scanning the page and quickly understood the mission.

> - Replacing “Learn More” with “Learn more about how to contribute.” And linking to the contribute page instead of the About page. One user selected this link to navigate to the Contribute page.

> - Adding additional context under “Bug Reporting,” “Bug Diagnosis” and "Site Outreach.” Although one user clicked one of the links without reading the text, three others read it and seemed to have a better understanding of the process.

<img src="https://cloud.githubusercontent.com/assets/4382193/23633452/a67e585e-027a-11e7-939b-aae503b427b7.png" />

**Comment by nj4710** [comment]
I would like to work on this :)

**Comment by zoepage** [comment]
@nj4710 Could you send the PR for #1401 first as you claimed it before? Thanks :)

**Comment by nj4710** [comment]
![site](https://cloud.githubusercontent.com/assets/13145287/23789499/12cbf75e-05a1-11e7-936e-a2d578160e99.jpg)
Hi @zoepage Few changes that I did. The images have credit at the bottom. Should we retain that??

**Comment by zoepage** [comment]
@nj4710 cool, thanks!

No, it shouldn't. 
Could you please send a PR, so we can discuss it in there as we go? :) 
Here you can find more information, about our submission guidelines: https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

If you have any questions, let me know.

**Comment by zoepage** [comment]
fixed in #1426
