### ISSUE TITLE
Add Contributor link to top navigation

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1404]
<img src="https://cloud.githubusercontent.com/assets/4382193/21939242/b968bef8-d973-11e6-8839-fba39a69accb.jpg" />

### Todo's
- [ ] create anchor we can link in top navigation to https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/home-page/join-us.html#L3
- [ ] Add contributors link to top navigation with the label `Contribute` https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/nav.html
- [ ] link to anchor in `join the team` section title
- [ ] add contributor SVG icon https://thenounproject.com/search/?similar=898865&i=346424 to link
- [ ] hide link description for responsive layout as it is right now & seen in following
(label should be hidden by default with same semantics, https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/navbar.css#L41)
<img src="https://cloud.githubusercontent.com/assets/4382193/22042177/e5a4e9d0-dcbe-11e6-817e-951c5bbc218a.png" /> (the icon should still be visible)

---
### Context
Follow up issue on https://github.com/webcompat/webcompat.com/issues/1281#issue-200691564.

**Comment by miketaylr** [comment]
> add contributor SVG icon https://thenounproject.com/search/?similar=898865&i=346424 to link

We were originally using an icon font, bug see also #899 to use inline SVG instead. This bug could tackle both at the same time, or just add the new SVG.

**Comment by heatherbooker** [comment]
@zoepage Did you want to use that exact icon? Where does the artist attribution go, or is there a nounproject account we can use?

**Comment by zoepage** [comment]
@heatherbooker if you have something different in mind, I am not committed to that one ;)

> Where does the artist attribution go, or is there a nounproject account we can use?

It goes here: https://github.com/webcompat/webcompat.com/blob/master/README.md#icons

**Comment by heatherbooker** [comment]
Awesome, thanks!

I went with the one you suggested - I just wondered if there was one more similar to the original screenshot! All good.

**Comment by zoepage** [comment]
@heatherbooker we'll add a different set of icons soon as shown here: https://github.com/webcompat/webcompat.com/issues/1374

So, no worries about the visual fit as it will shift anyway. ;)

**Comment by heatherbooker** [comment]
Okie doke. Can I vote on that one?! The diagnose bug icon on the issue you just posted? :D

**Comment by zoepage** [comment]
@heatherbooker sure, feel free to vote :)
