### ISSUE TITLE
Refactor bug submit form

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1547]
## Context
-> https://webcompat.com/issues/new & https://webcompat.com/?open=1

More Context: https://github.com/webcompat/webcompat.com/issues/1007#issuecomment-297720355 (please see the work week notes in the details)

**NOTE:** *There will NOT be a redesign yet as seen in the mockups.* We aim to change the form structure first as well as the wording of the labels. :)

## Todos
**Text**
- [x] Finalize wording of labels (https://github.com/webcompat/webcompat.com/issues/1007#issuecomment-297736870)
- [x] Figure out which values are optional / required

**HTML/CSS**
- [x] Switch upper grid cells in the form (as seen in mockups)
- [x] Split textarea in two different input fields. Add `Describe what was wrong?` and `How did you get there?` as replacement for `Expected behavior` and `Actual behavior`
- [x] Group inputs for browser / OS version
- [x] Change label of browser / OS version to `Is this information correct?`
- [x] Add `Did you test in another browser?` label and two radio buttons with [yes/no] options.
- [ ] Make new form information readable in issue template (https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/issue.html)

**TESTS**
- [ ] Update tests
- [ ] After this gets merged, follow up to check that the fix applied for #1552 does not get broken

**API/PYTHON/JS** 
- [x] Add fields for `Did you test in another browser?` radio buttons
- [x] Change textarea -> two input fields and store information
- [ ] Massaging the data before sending them to the issue template. The structure being slightly different. (https://github.com/webcompat/webcompat.com/issues/1547#issuecomment-298896321)
- [ ] Update form validation in bugform.js 

## Mockups

**Desktop**
![desktop hd](https://cloud.githubusercontent.com/assets/562354/25616704/9fdd5914-2f3e-11e7-9a07-f62755f29f67.png)

**Mobile**
![mobile portrait](https://cloud.githubusercontent.com/assets/562354/25616705/9fdf4652-2f3e-11e7-8496-bfa9516b5fe4.png)

**Comment by zoepage** [comment]
@adamopenweb @miketaylr @karlcow anything I forgot in the todos?

**Comment by miketaylr** [comment]
I added a "Update form validation in bugform.js" to the JS section, maybe there should be a "figure out what is optional/required" task as well?

**Comment by zoepage** [comment]
@miketaylr thanks. Also added the task.

**Comment by karlcow** [comment]
Added "Massaging the data before sending them to the issue template. The structure being slightly different."

**Comment by zoepage** [comment]
@karlcow thanks for the addition. could you make the todo a bit more specific as I am not sure what "massaging the data" means? 😁 Also just adding a comment here and linking it next to the todo works. Thanks! :)

**Comment by karlcow** [comment]
@zoepage creating the payload on the python side which is sent to GitHub. We have a form with multiple parameter which is creating a JSON payload that we are sending to GitHub.
See https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L161

**Comment by zoepage** [comment]
@karlcow thank you :)

**Comment by softvision-sergiulogigan** [comment]
Hi all,

I think that the last question in the form, "Did you test in another browser?" [Yes][No], should have at least 2 followup questions, if the answer is Yes:

[Yes] --> (Q1) Which one? (drop down list - Edge, Safari, Chrome etc) --> (Q2) Is the same as in [field for "Firefox 52"]? [Yes][No]

I think that if someone tries to reproduce an issue in another browser, will be ok with providing a little bit more information.

**Comment by softvision-oana-arbuzov** [comment]
Hi all,
I think a "Notes" text area would be nice to have, in case extra info is available (debugging/reproducibility rate...).

**Comment by miketaylr** [comment]
I think "how did you get there" should be a textarea, rather than input. It could even have placeholder text that mentions you can include any extra information, like @softvision-oana-arbuzov is suggestion.

**Comment by softvision-sergiulogigan** [comment]
Here's a wild thought we had:
What if the Screenshot placeholder would support *.zip files as well?
1st of all, this would help us filing issues more efficiently, but we think other reporters would like to attach not only screenshots, but also short videos of encountered issues (maybe of those that are harder to explain).

**Comment by miketaylr** [comment]
Yeah, zip can be scary. If we need to support videos, there are 3rd party solutions, or we can upload video assets directly to S3.

Other than video, what would you like to include in a zip @softvision-sergiulogigan?

**Comment by zoepage** [comment]
@softvision-sergiulogigan @softvision-oana-arbuzov 
Thank you for your suggestions! As we decided during the work week to stick with a small set of changes, I will add them to the next steps in combination with the refactor. 


(also @miketaylr @karlcow @adamopenweb)
To cross off the first 2 todo's, here is a final suggestion for the form.
* = required

```
  - Site URL* // label + input
      - e.g. https://example.com 
      
  - Type of bug* // fieldset -> label + checkboxes + labels
      - Desktop site instead of mobile site 
      - Site is not usable 
      - Design is broken 
      - Video or audio doesn't play
      - Something else
      
  - Please describe what was wrong.* // label + input
    - e.g. The video should have started after 3 sec.
    
  - How did you get there? // label + textarea
    - e.g. I've clicked the play button 42 times really fast. The player crashed and displayed the error message "D'oh! Something went wrong".

    - OR 1. I've clicked the play button 42 times really fast. 2. The player crashed. 3. It displayed the error message "D'oh! Something went wrong".
    
  - Is this information correct? // label + 2 input's (inputs get a checkmark if prepolluted with correct info. correct as in found user agent. we need a check here for UA and OS.) 
    - Browser version 
    - OS 
    
  - Did you test in another browser? // label + 2 checkboxes (don't pre-select)
    - Yes
    - No
    
  - Screenshot upload // label + input
  - report anonymously // button 
  - report as GitHub user (/report as xyz) // button, just show if logged in
  
```

**Comment by magsout** [comment]
love the new design of every element form. The buttons are much clear.

Super excited about the new design.

Good job @zoepage

**Comment by miketaylr** [comment]
Looks good!

Can you explain the following, for the report as GitHub user?

> button, just show if logged in

**Comment by zoepage** [comment]
@miketaylr this is the toggle between the labeling of the second button. The phrasing is misleading. 

When you are not logged in, you get the label "report as GitHub user". If you are "report as xyz".

**Comment by zoepage** [comment]
@adamopenweb suggested following for the `How did you get there?` textarea:

```
1. Log in
2. Fill out form details
3. Click submit
```

**Comment by zoepage** [comment]
Last call for feedback on labeling and optional / required. After we decided, @cch5ng said she'd love to take over and take care of the first steps. :)

@karlcow @miketaylr @adamopenweb

**Comment by miketaylr** [comment]
My only concern is the placeholder text in https://github.com/webcompat/webcompat.com/issues/1547#issuecomment-301755301. It might be confusing as-is, it feels a bit like an instruction to a user, rather than an example.

**Comment by adamopenweb** [comment]
@miketaylr I can see that. This area I'd particularly like to get better information from the user than we currently do (see incomplete bugs). Suggestions on how to accomplish that are totally welcome.

**Comment by zoepage** [comment]
@miketaylr @adamopenweb 
Not sure, if those are suggestions in the right direction.

```
1. I've tried to log in.
2. I've filled out the form details.
3. I clicked on the submit button.
4. Nothing happened. 

```

Or would you feel a free text without the steps more fitting?

**Comment by softvision-sergiulogigan** [comment]
We (Oana and I) feel like the "Describe what was wrong" and "How did you get there" field titles are a little bit fuzzy in terms of scope. We think that a regular user will not know how to correctly use the fields to communicate their findings. We ended up debating the field titles and examples given, in order to understand what to write there (we have a feeling that a regular user will not do/like that).

We suggest renaming the mentioned fields, so they will be more intuitive.
How about "What steps did you performed to get there?" (for the Steps to Reproduce part) and "Describe what was wrong" (for the Actual Results part)?

- What steps did you performed to get there? // label + textarea
e.g.
1 Log in
2 Fill out form details
3 Click submit

- Describe what was wrong.* // label + input
	e.g. The video should have started after 3 sec.


Furthermore, we think that naming the fields of the Environment section would be also a plus. We could use the current titles and page layout:

Is this information correct?
	- Browser / Version
		Firefox 52
	- Operating System
		MacOS X 10.12

**Comment by cch5ng** [comment]
hi, I had a question about form validation behavior. is this the expected behavior: if I select any field which is required, then validation will be run for all required fields (resulting in the display of warning messages for any required fields currently empty)?

if I then fix one field (like add a url) then should I expect the validation status should only be fixed for that field? thanks!

**Comment by cch5ng** [comment]
@miketaylr hi, is there an automated way to run the auth tests (to avoid having to key in the 2fa code)? I think one time a github bot was mentioned but I couldn't find it in the docs. if that is not currently used should it be ok to reorder the tests in tests/functional-all.js so the auth tests run at the beginning?

**Comment by karlcow** [comment]
@miketaylr will be replying. But I guess reordering is perfectly fine. Maybe there are sequences where we test the login/logout process, but apart of these, I think there is no issue.

Our privileged user on webcompat.com is @webcompat-bot

**Comment by cch5ng** [comment]
Hi, I wanted to propose a couple changes to the new bug report form validation behavior.


Currently, there is some behavior which I find a little unintuitive but I think was designed from the intention of being able to test input state with the intern tests.


Ex. one validation test from the old form was if you select the text area (with problem description), the JS would check whether the field above (required problem type radio buttons) had any button selected


I feel this is a little unintuitive because the user is getting an error message related to a field they might not have touched yet (maybe they like to do things out of order?)


These are a couple changes I would like to make and get feedback on:
1. For required text inputs/text areas, the main validation should be on itself. If the user selects the input and then moves away, there should be field validation on itself only (if required, not empty; if pattern matches required pattern) => this is mostly the current behavior


2. Enable the submit buttons by default but add a click event handler
On click, all fields should be validated (displaying errors if necessary and preventing the form data being submitted if there are errors currently)


I hope this would be more intuitive for when a field gets validated. It should still make radio buttons' state be testable.

**Comment by cch5ng** [comment]
@zoepage I'm not sure about this checkbox:

Make new form information readable in issue template 

currently I seem to be able to save a new issue, search for it and view its contents ok. also I can search for an older issue and view its contents ok as well. does the template still require updates? thanks!

**Comment by cch5ng** [comment]
hi, not sure who to ask, @karlcow or @magsout, but I had a question about this function, [checkParams()](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L139)


* from looking at the webcompat browser add-ons for firefox and chrome, I can see where the [urlParam](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L145) gets used
* I'm not clear, for the other variables, [problemType](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L157) and [details](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L163), are they only defined for testing purposes or is there another part of webcompat.com/addon tool where those report field values might get sent in the url?

**Comment by karlcow** [comment]
@cch5ng Honestly, I didn't remember. But looking at the blame should help us to find out.
https://github.com/webcompat/webcompat.com/blame/master/webcompat/static/js/lib/bugform.js#L153

It was added by @miketaylr when we worked on adding the type-media report. Basically videos issues are automagically detected and they propose the users to send a bug report to webcompat.com. When doing that the URL has a certain number of parameters which are prefilled. 
And it's why you see that.

**Comment by cch5ng** [comment]
thanks @karlcow for the info. is there a simple way for me to test the broken video scenario? I'm searching through recent issues but can't find one for video I can reproduce.

I'm not sure then if it is simplest to leave the code as is for the detail prepopulation
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L163 

I don't know how granular the info for the type-media report will be (does it need to be broken into the 2 separate fields for the form refactor... 1 description ... 2 steps to reproduce ?)

**Comment by cch5ng** [comment]
@zoepage while looking at #1552 I'm seeing that I have a current bug in my pr for this issue (#1547). I forgot to test the image upload and need to update where the link text gets added.

**Comment by karlcow** [comment]
> is there a simple way for me to test the broken video scenario?

@cch5ng yes http://safeschool.mon.bg/Videos/201705210928251574.mp4

![capture d ecran 2017-06-02 a 08 38 51](https://cloud.githubusercontent.com/assets/505230/26705113/f2940e12-476e-11e7-9482-e19c5a1c07b3.png)

Then if you click Report Site Issue, you get:

https://webcompat.com/issues/new?url=http%3A%2F%2Fsafeschool.mon.bg%2FVideos%2F201705210928251574.mp4%3FAspxAutoDetectCookieSupport%3D1&label=type-media&problem_type=video_bug&src=media-decode-error&details=Technical+Information%3A%0AError+Code%3A+NS_ERROR_DOM_MEDIA_METADATA_ERR+%280x806e0006%29%0AResource%3A+http%3A%2F%2Fsafeschool.mon.bg%2FVideos%2F201705210928251574.mp4

**Comment by cch5ng** [comment]
@karlcow thanks. that url provided the info I was looking for.

**Comment by cch5ng** [comment]
@karlcow where could I get the media type report tool? if I try to open http://safeschool.mon.bg/Videos/201705210928251574.mp4 in my browser (with webcompat addon), I don't see that Report Site Issue button. thanks.

**Comment by cch5ng** [comment]
update for [comment above](https://github.com/webcompat/webcompat.com/issues/1547#issuecomment-305340067) (about validation logic)

from looking at the bug report form behavior if you report an issue using a webcompat browser addon (or the broken video media type report), it seems more logical why the current validation logic works as it does. if majority of users are not reporting issues by starting at webcompat.com, I guess the validation makes sense.

**Comment by karlcow** [comment]
@cch5ng just open the URL in Firefox Nightly :) You will see it appearing.

**Comment by cch5ng** [comment]
@karlcow ok, I can see that button. thanks.

**Comment by cch5ng** [comment]
@karlcow I have a couple more questions. in form.py, there is a section towards the bottom:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L211
should I just assume that each new form field needs to be added as a new line and
it needs a key in the formdata (above), 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L199

in my working branch I am able to add an issue with the new form and open it from /issues/# and view it normally. I am also able to view older issues (created with the old form). does this mean I don't need to update an issues template? is the content being saved more like a string than per field?

**Comment by karlcow** [comment]
@cch5ng yes. The parameters are consumed by form.py and formatted in a blob of text. The cool thing with more detailed/atomic parameters is that it opens a window for a better html markup.

We just need to be careful on how our tests and our regex go through. We are parsing the payload body at a couple of places. If we have silent fails, it will be an opportunity to add more tests. :)

**Comment by miketaylr** [comment]
> I'm not clear, for the other variables, problemType and details, are they only defined for testing purposes or is there another part of webcompat.com/addon tool where those report field values might get sent in the url?

@karlcow already answered this, but yes we need those. These tests will fail without them (and that will break Firefox Nightly functionality): https://github.com/webcompat/webcompat.com/blob/master/tests/functional/reporting-non-auth.js#L258-L309

**Comment by miketaylr** [comment]
> hi, is there an automated way to run the auth tests (to avoid having to key in the 2fa code)? I think one time a github bot was mentioned but I couldn't find it in the docs. if that is not currently used should it be ok to reorder the tests in tests/functional-all.js so the auth tests run at the beginning?

@cch5ng I use @GIGANTOR's credentials to run auth tests and not have to mess with 2fa. It's in the "bot-staff" group which doesn't have write access to webcompat.com, so I'm not super worried about it. I believe you used to have access to those credentials, ping me on IRC if you'd like me to re-give them to you.

As for ordering, it shouldn't make a difference.

**Comment by karlcow** [comment]
@zoepage What the issue page is supposed to look like once the new data style has been created.

for now it looks like this:

http://localhost:5000/issues/706

![capture d ecran 2017-06-09 a 11 31 48](https://user-images.githubusercontent.com/505230/26958741-42fa86b8-4d07-11e7-95cb-4a70d2e7a495.png)

This is what I meant by:

> Massaging the data before sending them to the issue template. The structure being slightly different. (#1547 (comment))

**Comment by karlcow** [comment]
And when no tested in another browser has been selected.

![capture d ecran 2017-06-09 a 11 34 18](https://user-images.githubusercontent.com/505230/26958806-a01d7d50-4d07-11e7-8820-ece1d922be6b.png)

**Comment by zoepage** [comment]
@karlcow Ah! :) I'd say its okay like this. We can still change it, if it does not work for us?
