### ISSUE TITLE
Update Issue model notion of issue state to handle milestones

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1757]
Currently it reads labels.

https://github.com/webcompat/webcompat.com/blob/d2ba4dd1667801e09d4bd192b553fac50d485b59/webcompat/static/js/lib/models/issue.js#L47-L80

#886.

**Comment by miketaylr** [comment]
We still want a `stateClass` though, so the correct CSS classes get added to the templates. Maybe at some point it can be called `statusClass`.

**Comment by miketaylr** [comment]
TODO:

* [ ] listen for `change:milestone` method, rather than `change:labels` (it should exist....)
* [ ] read milestone from model milestone property, rather than labels list
* [ ] if an issue is closed state, the UI should show `Closed: Incomplete`, etc., rather than just Closed

**Comment by miketaylr** [comment]
* [ ] actually change state for certain milestones?

**Comment by miketaylr** [comment]
* [ ] file follow up bug to remove/figure out worksforme/fixed CSS classes (and if we need different classes/colors for the various closed statuses.
