### ISSUE TITLE
Make sure docs are up to date with labels vs milestones

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1759]
#886.

**Comment by karlcow** [comment]
I need to do that this week. And we are done.

**Comment by karlcow** [comment]
@miketaylr 

So I checked.

* [x] https://webcompat.com/contributors Nothing to change
* [x] https://github.com/webcompat/webcompat.com/wiki current wiki documentation is fine.
* [x] https://github.com/webcompat/webcompat.com/tree/master/docs nothing to change there too.
* [x] https://wiki.mozilla.org/Compatibility/Guide/Triage doesn't need any modifications.

The only thing we could **add** is on the wiki document the differences between labels and milestones. That said we don't document the current software architecture for labels.

I'm closing this issue.
