### ISSUE TITLE
Refactor: shared/ + stand alone

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1892]
This is a list of issues per unit or page.

Please grab one issue and push this into the `issues/1892` branch with the commit message mentioning `Issue #IssueNumber` to get the reference in the correct issue. 

- [x] #1883 - footer.html [done by @chaosmonster]
- [x] #1881 - nav.html + shared-nav-links.html [wip by @chaosmonster]
- [x] #1893 - issue-item.html
- [x] #1879 - remove bulb illustration [done by @Fischaela]
- [x] #1894 - layout.html [wip by @chaosmonster]
- [x] #1896 - error.html [done by @robinboehm]
- [x] #1902 - topbar.html [wip by @chaosmonster]
- [x] #1903 - addon-links.html [done by @robinboehm]
- [x] #1906 - about.html [done by @Fischaela]
- [x] #1907 - privacy.html [done by @Fischaela]

**Comment by chaosmonster** [comment]
I'll take #1883

**Comment by zoepage** [comment]
@robinboehm #1896

**Comment by chaosmonster** [comment]
I'll take #1902 while waiting for https://github.com/webcompat/design/pull/77

**Comment by robinboehm** [comment]
I'll take #1903

**Comment by zoepage** [comment]
@Fischaela claims #1879

**Comment by zoepage** [comment]
@chaosmonster #1881? or #1906 ?

**Comment by chaosmonster** [comment]
I will take #1881

**Comment by zoepage** [comment]
@Fischaela claims #1907
