### ISSUE TITLE
Refactor: user-activity/

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1895]
This is a list of issues per unit or page.

Please grab one issue and push this into the issues/1895 branch with the commit message mentioning Issue #IssueNumber to get the reference in the correct issue.

- [x] #1904 - user-activity.html
- [x] #1885 - reported-by-user.html
- [x] #1887 - user-mentions.html

**Comment by zoepage** [comment]
@lewiscowper I remember you working on this? Am I remembering it wrong?

**Comment by lewiscowper** [comment]
I was indeed @zoepage. Probably some time this weekend I'll have time to finish it up. :)

**Comment by zoepage** [comment]
sweet, thanks! didn't want to start before knowing to not sabotage your work. <3

**Comment by zoepage** [comment]
@lewiscowper ping? :)

**Comment by zoepage** [comment]
@lewiscowper wanna push your state? happy to take over? :)

**Comment by lewiscowper** [comment]
@zoepage have pushed to my fork issues/1895, (had some issue that I couldn't seem to authenticate to this github remote, but the commit/work is up on github somewhere now at least).

**Comment by zoepage** [comment]
Sweeeeeeeet, thanks!

**Comment by zoepage** [comment]
https://github.com/webcompat/webcompat.com/pull/1963
