### ISSUE TITLE
Refactor: /contributors

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1917]
This is a list of issues per unit or page.

Please grab one issue and push this into the issues/1917 branch with the commit message mentioning Issue #IssueNumber to get the reference in the correct issue.

- [x] #1911 - contribute.html
- [x] #1913 - diagnose-bug.html
- [x] #1914 - reproduce-bug.html
- [x] #1915 - site-outreach.html
- [x] #1916 - contributors.html

More context: https://github.com/webcompat/design/issues/48

**Comment by zoepage** [comment]
sweeeeeet!

**Comment by zoepage** [comment]
@denschub we need to add more routes here. could you help?

**Comment by zoepage** [comment]
done by #1917, follow up for content is #1933
