### ISSUE TITLE
Refactor: /home-page

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1932]
This is a list of issues per page.

Please grab one issue and push this into the issues/1932 branch with the commit message mentioning Issue #IssueNumber to get the reference in the correct issue.

- [x] #1931 - index.html
- [x] #1927 - browse-issues.html
- [ ] #1891 / #1898 - form [WIP by @denschub]
- [x] #1928 - hero.html
- [x] #1929 - join-us.html
- [x] #1930 - threesteps.html
