### ISSUE TITLE
Post-refactor tasks

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2017]
- [x] move CSS from design/docs to webcompat.com repository and replace old
- [x] change link to CSS in index
- [x] revert CSP and exclude github pages from white list
- [x] lint all files (+ #2031)
- [x] add back pre-linter (after #2031 was fixed)
- [x] move SVG folder after cleaning it out from unused SVG's
- [x] move SVG import script (and dependencies) to package.json and edit paths 
- [x] fix watch-grunt task for CSS (diff against master, jshint is undefined)
- [x] add `webcompat.dev.css` to linter (#2049)
