### ISSUE TITLE
Build global issues view

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#266]
Essentially the Flask/Backbone guts of whatever gets designed in https://github.com/webcompat/webcompat.com/issues/169
- [x] issues displayed
  - [x] refactor issue models
  - [x] write view code for issues to be shown
  - [ ] ~~pull in "team"~~ #288
- [x] issues filtering
  - [ ] issue count in filters #291
  - [x] make reusable dropdown component
  - [x] teach dropdown component about logged in state
  - [x] is-active class for filter button
  - [x] ~~make filter dropdown interactive~~
  - [x] clicking ouside filter closes it
  - [x] ~~make filter dropdown update search query~~
  - [x] ~~make clicking filter button update search query~~
  - [x] add toggle behavior to "remove" filter
- [x] issues sorting
  -  [x] ~~make sort dropdown update search query~~
- [x] issues search
  - [x] add endpoint for search API
  - [x] normalize data returned from search API to match what our model expects
  - [x] update/re-render issues based on clicking filter (depends on having search in place)
  - [x] arbitary search
  - [x] clicking on label updates search & issues
  - [x] #308, if searchbox is empty, render default
  - [x] automatically search as user types (debounced)
- [x] make sure updating search via filter + dropdown isn't mutually destructive
- [x] remove transparent "search for everything" approach. (meaning, every filter/sort operation shouldn't update the search box... even if we end up using the search API for that, I think it will be too confusing)
- [x] clicking on category button (untriaged, needs diagnosis, etc.) updates results.
- [x] pagination
  - [x] return `Link` header with XHR responses
  - [x] write logic to track `rel=next`, `rel=previous`, etc. from client
  - [x] when at first, disable previous, when at last disable next
  - [x] re-render when asking for next page
  - [x] add pagination support to relevant API endpoints
  - [x] generalized Link href parsing and an endpoint to handle that.
