### ISSUE TITLE
AB testing of new form design plan

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2954]
This issue defines a plan to evaluate if the new form design should replace the current form.

**Launch date**: <s>16 Oct (assuming everything is ready)</s> 24 Oct
**Duration**: ~4 weeks
**Audience exposure**: we'll deploy to a very small % to ensure that nothing is broken, then ramp up over time, up to 50%. e.g, 3% -> 15% -> 30% -> 50%
**Go / No Go decision**: The goal of the form redesign is to have a 30% improvement in "valid" bugs (defined as bugs that graduate from needstriage to needsdiagnosis) week over week. That's a high number!

ACTION ITEMS: 
* OI to update the pull requests with fixes before the end of the week
(We should probably document all blockers as well here. )
* Mike to figure out how to tell tests which form to test against
* Adam to figure out reporting of valid % for each branch of the experiment (defined as number of issues that graduate from needstriage to needsdiagnosis), so we can determine if it actually works. 
* Christos to make sure Google Analytics track behavior and clicks in the new form (this needs a bug, because it will require JS changes)
* Some kind of QA so we have confidence it actually works before launching

Blocker Bugs:
* [x] Add ab testing environment variables to server: https://github.com/webcompat/webcompat.com/issues/2956
* [x] Be able to identify reports that come from the new form https://github.com/webcompat/webcompat.com/issues/2940
* [x] Tell tests to only run v1 of form https://github.com/webcompat/webcompat.com/issues/2947

**Comment by softvision-sergiulogigan** [comment]
> * Some kind of QA so we have confidence it actually works before launching

@miketaylr we would love to do some manual testing here
CC @softvision-oana-arbuzov @cipriansv

**Comment by miketaylr** [comment]
> @miketaylr we would love to do some manual testing here

Cool, thanks. :) I'll bring it up in the next meeting.

**Comment by miketaylr** [comment]
OK, we can close this now.
