### ISSUE TITLE
Issue Labels color contrast

### ISSUE THREAD

**Issue by andrewmcgivery** [webcompat/webcompat.com#482]
Many of the labels for issues do not have enough color contrast are are causing color contrast errors.

Here's a list of of labels that need some work... I have listed the current colors and colors that would pass AAA level color contrast. We could also go for AA level if we don't want to go all out. Up to you guys. I would suggest going for AA though.

Not sure if you guys want to go for these colors or do a further assessment. Some of these colors aren't the prettiest. :)

Also, it's a fairly big list so it make take a bit of work to solve all of these.

Label  | Current Color | Passing Color (AAA Standard)
------------- | -------------|-------------
"Untriaged Issue"  | #6fc7fa | #437d9e
"Needs Diagnosis" | #ff8364 | #b75c46
"Ready for Outreach" | #a1ebbf | #558066
"Closed" | #799299 | #657a80 
"firefox"  | #FF4E00 | #a42f00
"ie" | #00B9EC | #00617d
"mobile" | #009800 | #006800
"updated" | #ededed | #595959
"worksforme" | #d4c5f9 | #5c556e
"fixed" | #009800 | #006800
"ucweb" | #f7c6c7 | #6a5354
"iceweasel" | #0052cc | #0050c8
"ios" | #0bd318 | #026806
"sitewait" | #006b75 | #00636c
"contactready" | #A1EBBF | #3f604d
"android" | #28ACBB | #13626b
"safari" | #1B9BF6 | #0c5c95
"chrome" | #F16A5A | #943e34
"needsinfo" | #fbca04 | #6d5601
"invalid" | #e6e6e6 | #595959
"duplicate" | #cccccc | #595959

NOTE: "updated" label color also affects labels ie11, chromium, internet, nightly, and mozilla.

**Comment by miketaylr** [comment]
Yeah, I like the icons as well.

I'm fine with ditching label colors @calexity -- maybe we just have a gray/whatever underline to indicate it's a clickable filter?

**Comment by calexity** [comment]
Yes! Our medium gray should be perfect.

**Comment by calexity** [comment]
@karlcow thank you for pulling this one up!

It looks like we addressed the colors and we just haven't put them in the CSS. I would do that myself, but this app is far from the days when I could run it:)

- [ ] New - (soft red) #ff8364 with black #000 text
- [ ] Needs diagnosis - (gold) #efce82 with black #000 text
- [ ] Needs contact - (light green) #b9edce with black #000 text
- [ ] Needs outreach - (teal blue) #7abce1 with black #000 text
- [ ] Waiting - (light blue) #b0daf0 with black #000 text
- [ ] Closed - (gray) #c5d1d5 with black #000 text

See this comment for more: https://github.com/webcompat/webcompat.com/issues/484#issuecomment-68214379

Is there something else I'm leaving unfinished here @karlcow?

**Comment by magsout** [comment]
@calexity 

labels are already using these colors

```css

:root {
  --wc-state-new: #ff8364; 
  --wc-state-need: #efce82; 
  --wc-state-needcontact: #b9edce; 
  --wc-state-ready: #7abce1; 
  --wc-state-sitewait: #b0daf0; 
  --wc-state-close: #c5d1d5; 
}
```

or maybe I missed someting ?

**Comment by magsout** [comment]
@andrewmcgivery how I can test if a color pass AAA level color contrast ?

**Comment by andrewmcgivery** [comment]
I tend to use this tool:

http://webaim.org/resources/contrastchecker/

That help?

**Comment by magsout** [comment]
@andrewmcgivery oh thanks, sorry I didn't see your message

**Comment by magsout** [comment]
I tried the filters with colors proposed by @andrewmcgivery 

## Before:
![capture d ecran 2015-10-13 a 22 58 46](https://cloud.githubusercontent.com/assets/1997108/10468226/2d69f2ce-71fe-11e5-80bf-36b294009b05.png)

## After:
![capture d ecran 2015-10-13 a 22 57 53](https://cloud.githubusercontent.com/assets/1997108/10468233/39d4997e-71fe-11e5-8cff-6b2b9ca4a7c2.png)

Filters are more visible. But I liked the progression of color before. @adamopenweb do you think there is a way to keep the old color but with good contrast ?

**Comment by miketaylr** [comment]
I also prefer the before colors... does contrast improve if we change the text from white to black?

**Comment by andrewmcgivery** [comment]
@miketaylr Changing white text to black will probably make most of the original colors pass actually.

**Comment by miketaylr** [comment]
The current design is a little different, but when you hover or select the filter button there's still the low contrast white color. Let's change it to be bolder and maybe that'll pass.

**Comment by miketaylr** [comment]
ping @magsout
